### ISSUE TITLE
Problema con pd.merge para tablas con diferente número de filas

### ISSUE THREAD

**Issue by APaloma710** [DCIDA2019/dcida2020ii-APaloma710#1]
Una de las preguntas descriptivas que planteamos la semana pasada fue:
"Promedio de la tasa de muerte en países con densidad de camas menor a 5 camas/1000 habitantes"

Para responder a tal pregunta tengo que obtener información de dos tablas diferentes que tienen diferente número de columnas y diferente número de filas. He tratado de utilizar la función 'pd.merge' para hacer una sola tabla con información de tasa de muerte e información sobre densidad de camas y a partir de ella filtrar los datos que necesito, sin embargo, la función 'pd.merge' despliega una tabla con únicamente dos filas, cuando las listas originales tienen más de 170 filas; quisiera saber si sabes a qué se debe esto ó si hay otro modo de 'juntar' información de ambas tablas.

El notebook se llama Answers.ipynb, las celdas donde se ve el problema son de la 145-147.

**Comment by alxogm** [comment]
@APaloma710 resolviste el problema? o sigue estando?

**Comment by APaloma710** [comment]
@alxogm Si Alma, gracias. Utilicé el comando que mi compañero expuso en el reporte; era cuestión de explorar los parametros de "pd.merge".
