### ISSUE TITLE
Problema instalando astropy

### ISSUE THREAD

**Issue by APaloma710** [DCIDA2019/dcida2020ii-APaloma710#2]
Hola @alxogm, he estado intentando instalar astropy y algunos complementos necesarios para astropy, pero no puedo instalar ni actualizar nada en mi equipo, es un problema de mi computadora no de GitHub ni Jupyter, solo que ya he intentado varias soluciones que encuentro en la web y  ninguna funciona, tal ves tú tengas alguna idea de cómo solucionarlo; el error que me arroja la terminal dice lo siguiente:

E: Tipo «<!DOCTYPE» desconocido en la línea 1 de la lista de fuentes /etc/apt/sources.list.d/medibuntu.list
E: No se pudieron leer las listas de fuentes.

esto resulta de teclear el comando para instalar pytest:

sudo apt-get install -y python-pytest

que es uno de los requerimientos para astropy.

Alguna idea de cómo solucionarlo?
Gracias de antemano

Paloma

**Comment by APaloma710** [comment]
Ya lo solucioné, gracias de cualquier modo.

**Comment by alxogm** [comment]
que bueno que lo resolviste, como tip, este es justo el tipo de problemas que se resuelven al usar instalaciones en ambientes, con miniconda, como vimos en clase :D. 

Saludos 
Alma
